# fly.toml app configuration file generated for site-wild-smoke-1175 on 2024-08-12T11:15:35-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'site-wild-smoke-1175'
primary_region = 'gru'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
